-- Airdrop proof storage (#914)
-- Stores finalized Merkle proofs generated by airdrop-finalize script

CREATE TABLE pl_airdrop_proofs (
  address TEXT PRIMARY KEY,
  amount TEXT NOT NULL,               -- wei amount as string (bigint precision)
  proof TEXT NOT NULL,                 -- JSON-stringified array of bytes32 hashes
  merkle_root TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
